### ISSUE TITLE
@nogc?

### ISSUE THREAD

**Issue by Herringway** [dlang-community/D-YAML#113]
Would like to get some thoughts on this before I put much work into it.

Many parts of this library are marked `@nogc`. However, despite that, this library cannot be used in `@nogc` code. Some (limited) testing also shows that any performance gains from this are minimal.

These parts of D-YAML depend on modified copies of phobos functions, making this library quite a bit larger than it needs to be.

My proposal is to completely remove the redundant functions and remove any `@nogc` annotations that are no longer valid, making this library noticeably slimmer.

**Comment by wilzbach** [comment]
Yep removing the redundancies is a great idea. Thanks!
