### ISSUE TITLE
findPair isn't being automatically inferred as @safe

### ISSUE THREAD

**Issue by jpiles** [dlang-community/D-YAML#119]
When compiling as a dependency, I get the following error:

> ../../../../.dub/packages/dyaml-master/dyaml/source/dyaml/node.d(726,36): Error: @​safe function dyaml.node.Node.opIndex!string.opIndex cannot call @​system function dyaml.node.Node.findPair!(string, cast(Flag)true).findPair
> ../../../../.dub/packages/dyaml-master/dyaml/source/dyaml/node.d(590,38): Error: template instance `dyaml.node.Node.opIndex!string` error instantiating
> ../../../../.dub/packages/dyaml-master/dyaml/source/dyaml/node.d(1837,35):        instantiated from here: get!(const(string), cast(Flag)false)
> ../../../../.dub/packages/dyaml-master/dyaml/source/dyaml/node.d(521,39):        instantiated from here: equals!(cast(Flag)true, const(string))
> ../../../../.dub/packages/dyaml-master/dyaml/source/dyaml/node.d(2147,33):        instantiated from here: opEquals!string
> ../../../../.dub/packages/dyaml-master/dyaml/source/dyaml/node.d(2080,24):        ... (4 instantiations, -v to show) ...

The problem is that apparently findPair is not being inferred as safe. If I just add the `@safe` attribute manually [here](https://github.com/dlang-community/D-YAML/blob/master/source/dyaml/node.d#L2132), it works as expected.

**Comment by BBasile** [comment]
also with D-YAML ~master ? the trunk includes many work on `@safe`

**Comment by jpiles** [comment]
Yes, I was trying with `~master`. I just tested it again, and it seems a problem with dmd not inferring @safe when it should (as proven by the fact that I can add it manually and it compiles).

Still, if opIndex is safe, wouldn't it make sense to force findPair to be safe as well?

**Comment by BBasile** [comment]
Yes. Ping @Herringway. Seems that this is another case of mutually dependent templatized function making `@safe` inference failing.
