### ISSUE TITLE
Segfault on newline at the end of doc

### ISSUE THREAD

**Issue by tchaloupka** [dlang-community/D-YAML#123]
I found that wit some files I got a segfault.
I've made a simple test to reproduce:

```D
import std.stdio;
import dyaml;

void main()
{
	enum yml = `foo:
  f: 42
`;
	auto root = Loader.fromString(cast(char[])yml).load();
	writeln(root);
}
```

When I remove the last newline from yaml, it is ok.
GDB points to this line: https://github.com/dlang-community/D-YAML/blob/master/source/dyaml/reader.d#L567

Tested on Fedora 27 with dmd-2.079.0 and dmd-2.079.1

**Comment by Herringway** [comment]
Loader expects the mutable array passed to it to actually be mutable. Casting a string literal to char[] doesn't actually make it mutable, so you're getting a segfault when it tries to write to a read-only segment of memory. Replacing `cast(char[])yml` with `yml.dup` makes the problem go away.

**Comment by tchaloupka** [comment]
Thx
