### ISSUE TITLE
Update Meson build version number

### ISSUE THREAD

**Issue by russel** [dlang-community/D-YAML#173]
Sadly Meson version numbers cannot have alpha etc. in them, but perhaps just set it to 0.7.0

**Comment by BBasile** [comment]
Meson is not SemVer compliant ?

**Comment by BBasile** [comment]
BTW, it must be obvious but 0.7.0-alpha-1 is just for testing. I'm sorry if it doesn't allow MESON users to test or prepare the transition. We're opened to solution if any. Again pign @ximion who IIRC handle the MESON thing so far.

**Comment by russel** [comment]
It would be great if @ximion could join in as advisor with the Meson stuff on Unit-Threaded and DInotify as well so we can get all D libraries consistent in their builds. For now I will assume D-YAML is a paradigm.

**Comment by BBasile** [comment]
> 0.7.0-alpha-1

sorry i made a typo, it's `0.7.0-alpha.1` damn.

**Comment by russel** [comment]
```
meson.build:52:0: ERROR:  Invalid Shared library version "0.7.0-alpha.1". Must be of the form X.Y.Z where all three are numbers. Y and Z are optional.
```

:-(

**Comment by russel** [comment]
Pull request #174
