### ISSUE TITLE
Fix compilation errors with -dip1000

### ISSUE THREAD

**Issue by Herringway** [dlang-community/D-YAML#184]
Some are simple - scope on some parameters, etc.

Others are not. Something weird is going on with -dip1000 and dyaml.emitter - the delegates created there appear to gain random attributes (const delegates? nothrow delegates that call enforce() without issue? what...?) and require explicit casting to their real type to work as expected.

RedBlackTree is also unusable `@safe`ly when -dip1000 is specified.

**Comment by Herringway** [comment]
Update - the entire batch of emitter errors go away if const is removed from dyaml.emitter.Emitter.expectNothing. what...?

**Comment by Geod24** [comment]
Found [this](https://issues.dlang.org/show_bug.cgi?id=22289) while (quickly) looking into this issue.
