### ISSUE TITLE
Possible broken link

### ISSUE THREAD

**Issue by russel** [dlang-community/D-YAML#190]
On the page https://dyaml.dpldocs.info/v0.7.0/dyaml.constructor.html I clicked the link in the introduction paragraph to get to the tutorial and it took me to  https://dyaml.dpldocs.info/vtutorials/custom_types.html which displayed the message "The project build failed. copy/paste this link to adam so he can fix the bug."

**Comment by BBasile** [comment]
Thanks. Unfortunately the change won't be reflected because for now we cant force update of the dpl sites.
Target would be https://dlang-community.github.io/D-YAML/.
