### ISSUE TITLE
Linking fails when building with dub with the `unittest-cov` build type

### ISSUE THREAD

**Issue by ColdenCullen** [dlang-community/D-YAML#20]
When building a project which relies on D-YAML in `unittest-cov` build mode, linking fails citing multiple undefined references to a symbol `__coverage`.

**Comment by MartinNowak** [comment]
I think it's a compiler bug. [Issue 13742](https://issues.dlang.org/show_bug.cgi?id=13742 "undefined reference to __coverage")

**Comment by wilzbach** [comment]
Hmm it seems that `dub` has found a way to workaround this as

```sh
dub test -b unittest-cov
```

works fine.
As the compiler bug is filled, I am going to close this right now, but please feel free to reopen if this still persists.

**Comment by BBasile** [comment]
it still fails when _debugInfo_ are generated. It works because the build types are customized with _debugInfoC_ (remove the _C_ of the `debugInfoC` in the description, then `dub test` restart failing).
