### ISSUE TITLE
Overzealous size assert in node

### ISSUE THREAD

**Issue by thewilsonator** [dlang-community/D-YAML#205]
[This assert](https://github.com/dlang-community/D-YAML/blob/master/source/dyaml/node.d#L188) trips when correcting alignment of the store field in https://github.com/dlang/phobos/pull/6790

**Comment by BBasile** [comment]
What should be the new minimal size ?

**Comment by thewilsonator** [comment]
See https://github.com/dlang/phobos/pull/6790#issuecomment-446164949 it may not have to change.

**Comment by joakim-noah** [comment]
The size of `real` varies by CPU and libc, but I agree this seems a silly check.

**Comment by Herringway** [comment]
yeah, these checks were a waste of time and space
