### ISSUE TITLE
Replace std.stream dependency in Emitter/Dumper

### ISSUE THREAD

**Issue by kiith-sa** [dlang-community/D-YAML#25]
Similarly to parsing, emitting should write to memory instead of std.stream. Once done, deprecate the std.stream dependent APIs.

**Comment by Herringway** [comment]
as of dmd 2.069, using std.stream causes the compiler to emit deprecation warnings stating that removal is planned for october 2016

**Comment by tmccombs** [comment]
I don't think this is an  issue anymore. The only reference I can find to std.stream is in the comments.

**Comment by wilzbach** [comment]
I think this has been fixed as part of 0.5 -> closing
