### ISSUE TITLE
Use of std.sumtype.SumType instead of std.variant.Algebraic

### ISSUE THREAD

**Issue by tom-tan** [dlang-community/D-YAML#281]
Currently `Node` type internally uses [`std.variant.Algebraic`](https://dlang.org/phobos/std_variant.html#.Algebraic) but the official document says it becomes outdated.

Is there a plan to migrate from `Algebraic` to [`std.sumtype.SumType`](https://dlang.org/phobos/std_sumtype.html) or can I send a pull request for it?
IMO it is worth doing because it enables D-YAML to work with attributes such as `pure`.

**Comment by Herringway** [comment]
It is something I wanna do eventually, but at the moment it doesn't really add a lot of value by itself. There are a few other dependencies that block pure, like std.regex, and that doesn't appear to be changing anytime soon...
