### ISSUE TITLE
D-YAML does not support escaped slashes in strings

### ISSUE THREAD

**Issue by Geod24** [dlang-community/D-YAML#302]
JSON optionally allows forward slashes to be escaped to prevent against some attack.
When trying to parse JSON that contains escaped forward slashes, D-YAML errors out:

```
dyaml.scanner.ScannerException@source/dyaml/scanner.d(1440): While scanning a double quoted scalar
file /home/webfreak/.dub/settings.json,line 3,column 9
found unsupported escape character /
file /home/webfreak/.dub/settings.json,line 3,column 17

----------------
source/dyaml/scanner.d:1440 pure @safe void dyaml.scanner.Scanner.scanFlowScalarNonSpacesToSlice(const(dyaml.style.ScalarStyle), const(dyaml.exception.Mark)) [0x563800947378]
source/dyaml/scanner.d:1356 pure @safe dyaml.token.Token dyaml.scanner.Scanner.scanFlowScalar(const(dyaml.style.ScalarStyle)) [0x563800946de9]
source/dyaml/scanner.d:647 pure @safe void dyaml.scanner.Scanner.fetchFlowScalar!(5).fetchFlowScalar() [0x563800948a29]
source/dyaml/scanner.d:244 @safe void dyaml.scanner.Scanner.fetchToken() [0x563800943248]
source/dyaml/scanner.d:183 @safe bool dyaml.scanner.Scanner.empty() [0x56380094300d]
source/dyaml/scanner.d:174 @safe const(dyaml.token.Token) dyaml.scanner.Scanner.front() [0x563800942f78]
```

CC @WebFreak001

**Comment by Herringway** [comment]
That is one of the JSON compatibility features that were added to YAML 1.2, which we don't really support yet. It should be a small and easy fix though

**Comment by Geod24** [comment]
https://github.com/dlang/dub/pull/2349

Will submit here soon.

**Comment by WebFreak001** [comment]
I tried to add it to escapes.d, but I couldn't really manage to create a test for that in the testing framework (I never managed to make an unknown escape break the tests)

**Comment by Geod24** [comment]
Yeah I spent a bit of time trying to understand what was going on then gave up and just wrote the module.
IMO D-YAML tests are not unittest, they are integration tests, because they do file IO.
I submitted https://github.com/dlang-community/D-YAML/pull/303 to fix this issue where I use a simple unittest.
