### ISSUE TITLE
Cannot store time

### ISSUE THREAD

**Issue by rcorre** [dlang-community/D-YAML#45]
I'd like to read a timestamp that looks like `HH:MM:SS` into a `TimeOfDay`, but the type seems to be parsed inconsistently:

```
writeln(Loader.fromString("0:20:15".dup).load().as!string);
writeln(Loader.fromString("20:20:15".dup).load().as!string);
```

prints:

```
0:20:15
73215
```

The former seems to be a `string`, the latter a `long`. `.as!SysTime` doesn't work on either.

**Comment by Herringway** [comment]
Unfortunately, YAML doesn't define a TimeOfDay-compatible timestamp format. I recommend you store the timestamp as a string and use a constructor/resolver pair to handle it. 

As for the inconsistent parsing... yeah, that'll need to be fixed and will likely come along with the YAML 1.2 support. Neither of those examples will be parsed as string scalars, though - you'll need to enclose them in quotes. ie. `"\"20:20:15\""`
