### ISSUE TITLE
Make isString, isBool, isType!T, etc public

### ISSUE THREAD

**Issue by WebFreak001** [dlang-community/D-YAML#47]
Currently these functions are only accessibly because of a bug in dmd: https://github.com/kiith-sa/D-YAML/blob/master/source/dyaml/node.d#L1643-L1659

I need them for identifying mixed nodes like these:

``` yaml
a:
- 5
- test
- b: 4
  c: 3
```

Would be nice to actually have them public

**Comment by BBasile** [comment]
What's up with this issue ? At first glance these alias seems to be public, right ?

**Comment by ZombineDev** [comment]
I think this can be closed, now that https://github.com/dlang-community/D-YAML/commit/22c432fb52b4dfdc9a0872e9a9ae2a0ec7e2e2b5 has been merged for some time.
