### ISSUE TITLE
With latest dmd 2.072.0 it is impossible to compile

### ISSUE THREAD

**Issue by Kozzi11** [dlang-community/D-YAML#48]
There are many deprecation, but these are errors:
	source/dyaml/emitter.d(1011,13): Error: field ScalarAnalysis.scalar cannot modify misaligned pointers in @safe code
	source/dyaml/event.d(230,5): Error: field Event.anchor cannot access pointers in @safe code that overlap other fields
	source/dyaml/event.d(231,5): Error: field Event.tag cannot access pointers in @safe code that overlap other fields
	source/dyaml/loader.d(186,43): Error: cast from void[] to ubyte[] not allowed in safe code

**Comment by Timoses** [comment]
^ Same issue here.

**Comment by Kozzi11** [comment]
there is a pull request https://github.com/kiith-sa/D-YAML/pull/49 but @kiith-sa seems inactive, maybe is time to fork this project

**Comment by ondravo** [comment]
I have the same problem :( any progress with this issue?

**Comment by Timoses** [comment]
If you are using dub you might try the "add-overwrite" tool to point to https://github.com/ZombineDev/D-YAML/tree/fix-compilation-with-dmd-2-072. However, I'm having the issue: https://github.com/dlang/dub/issues/779 .

**Comment by BBasile** [comment]
fixed this spring during the move to the organaization afaik
