### ISSUE TITLE
Submit Sociomantic fixes

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [dlang-community/D-YAML#56]
We have a [D-YAML fork](https://github.com/sociomantic-tsunami/D-YAML/commits/master) at Sociomantic with a few extra fixes that we should submit.

I sent you an invitation, @mihails-strasuns-sociomantic

**Comment by leandro-lucarella-sociomantic** [comment]
Thanks for taking care of this! I'll wait until @nemanja-boric-sociomantic is back from vacations to verify  all the fixes we had are now in the new repo and then close this and remove our fork.

**Comment by mihails-strasuns-sociomantic** [comment]
I have already switched https://github.com/sociomantic-tsunami/neptune/ to use D-YAML from this repo and it works with no issues. @leandro-lucarella-sociomantic you may have confused this with harbored-mod.

**Comment by leandro-lucarella-sociomantic** [comment]
Ah, yeah, I mixed both up, sorry!
