### ISSUE TITLE
Broken with dmd-nigthly

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/D-YAML#63]
https://github.com/dlang/dmd/pull/6839 fixed some holes in the safety system. Unfortunately D-YAML is affected:

```
source/dyaml/emitter.d(614,20): Error: address of variable this assigned to this with longer lifetime
source/dyaml/emitter.d(639,20): Error: address of variable this assigned to this with longer lifetime
```

For the next days I am a bit low on time, so if anyone has time to prepare fix, please go for it ;-)

**Comment by BBasile** [comment]
There's nothing to fix in D-YAML. This is a DMD regression
