### ISSUE TITLE
on as key is dumped as 'on'

### ISSUE THREAD

**Issue by gizmomogwai** [dlang-community/D-YAML#86]
e.g. travis ghpages deploy likes:

    on:
      branch: master

if i write this with dyaml i get 'on' ...
i think its not necessary to escape on, On, Off, .. on the left side of a colon.

**Comment by Herringway** [comment]
It is. YAML 1.1 allows types other than strings to be used as keys. `[0,1,2]: "hi"` is legal, for example.
`on` (without quotation marks) is considered to be a boolean value - `true`.

However, YAML 1.2 only recognizes `true` and `false` as boolean values, so this won't be an issue once #110 is complete (and assuming Travis-CI supports YAML 1.2 as well)

**Comment by gizmomogwai** [comment]
So this is more a travis issue? sorry for disturbing :)

**Comment by Herringway** [comment]
possibly. does travis-ci fail to recognize configurations where the `on` key is quoted?

**Comment by gizmomogwai** [comment]
don't know yet ... have to check.
