### ISSUE TITLE
Dumping without BOM

### ISSUE THREAD

**Issue by majiang** [dlang-community/D-YAML#88]
I'd like to dump some document to YAML file in UTF-8 without BOM, but emitter.d always writes BOM.  Is there any plan or obstacle to support, or workaround for this?

**Comment by BBasile** [comment]
If you can, make a PR. No BOM is often assumed to be "UTF-8 without BOM" so i don't see any problem.
Also UTF-8 is recommended for YAML (section 5.2 of specs)

**Comment by BBasile** [comment]
I don't believe it's a breakage because code using stuff emitted by D-YAML should really process BOM as an optional thing __anyway__. But maybe other won't agree, i cant say.

**Comment by majiang** [comment]
Opened #89
